# Generated by Django 4.2.14 on 2024-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='图标')),
                ('module_name', models.CharField(default='', max_length=100, verbose_name='所属系统模块')),
                ('category', models.CharField(choices=[('systemtools', '系统工具'), ('environments', '运行环境'), ('database', '数据库')], max_length=100, verbose_name='类别')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='英文标识')),
                ('name_cn', models.CharField(max_length=100, verbose_name='名称')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('dev_type', models.SmallIntegerField(choices=[(1, '官方'), (2, '第三方')], verbose_name='组件类型')),
                ('dependent', models.TextField(blank=True, null=True, verbose_name='依赖组件')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('status', models.SmallIntegerField(choices=[(1, '未安装'), (2, '已安装'), (3, '已禁用')], default=1, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('download_url', models.TextField(blank=True, null=True, verbose_name='下载链接')),
            ],
        ),
    ]
